# analysis_options.yaml
# ------------------------------------------------------------------
# Lint rules + analyzer settings for Nurse OS
# ------------------------------------------------------------------

include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/mock_data/**
    - lib/services/**
    - lib/state/**
    - lib/widgets/vitals_**
    - lib/widgets/vitals*
    - lib/screens/vitals_**
    - lib/screens/care_plan_screen.dart
    - lib/screens/patient_detail_screen.dart
    - lib/widgets/care_plan_section.dart
